server:
  port: 8765
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  hystrix:
    timeoutInMilliseconds: 60000
feign:
  hystrix:
    enabled: true

