server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/SDUxiaoma/UAffairsConfig
          searchPaths:
          username: 1666188122@qq.com
          password: mzg...8535933570
      label: master

