server:
  port: 8864
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  hystrix:
    timeoutInMilliseconds: 60000
spring:
  application:
    name: rabbitmq-queue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: uaffairs
    password: 1666188122


