server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  hystrix:
    timeoutInMilliseconds: 60000
spring:
  application:
    name: service-ribbon
  data:
    hbase:
#      quorum: 116.196.105.245:2181
      quorum: master,slave1
      rootDir: hdfs://master:8020/hbase
      nodeParent: /hbase
